server {
    listen 80;
    server_name _;

    root /usr/share/nginx/html;
    index index.html;

    location = /index.html {
        add_header Cache-Control "no-cache, no-store, must-revalidate";
        try_files /index.html =404;
    }

    location = /_app/version.json {
        add_header Cache-Control "no-cache";
        try_files $uri =404;
    }

    location /_app/immutable/ {
        add_header Cache-Control "public, max-age=31536000, immutable";
        try_files $uri =404;
    }

    location /_app/ {
        add_header Cache-Control "no-cache";
        try_files $uri =404;
    }

    # SPA routing
    location / {
        add_header Cache-Control "no-cache, no-store, must-revalidate";
        try_files $uri $uri/ /index.html;
    }

    # Proxy backend Django
    location /api/ {
        proxy_pass http://backend:7999/presenze/api/;

        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;

        proxy_redirect off;
    }
     # Django static files (admin, templates)
    location /static/ {
	alias /usr/share/nginx/static/;
	expires 30d;
	add_header Cache-Control "public, immutable";
    }

    # Optional Django media files
    location /media/ {
        proxy_pass http://backend:7999/media/;

        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;

        proxy_redirect off;
    }


    # Legacy backend path
    location /presenze/ {
        proxy_pass http://backend:7999/presenze/;

        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;

        proxy_redirect off;
    }
}

