# Generated by Django 5.2.6 on 2025-12-30 15:58

import django.contrib.postgres.fields
import django.db.models.deletion
import django.utils.timezone
import presenze.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Utente',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.BigAutoField(db_column='U_ID', primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(db_column='password_hash', max_length=128)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('dati_anagrafici', models.JSONField(blank=True, default=dict)),
                ('data_creaz', models.DateTimeField(default=django.utils.timezone.now)),
                ('data_upd', models.DateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'Utente',
            },
        ),
        migrations.CreateModel(
            name='Automobile',
            fields=[
                ('id', models.BigAutoField(db_column='A_ID', primary_key=True, serialize=False)),
                ('marca', models.CharField(max_length=100)),
                ('alimentazione', models.CharField(max_length=50)),
                ('descrizione', models.CharField(blank=True, max_length=255)),
                ('data_creaz', models.DateTimeField(default=django.utils.timezone.now)),
                ('data_upd', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'Automobile',
                'indexes': [models.Index(fields=['marca', 'alimentazione'], name='Automobile_marca_402994_idx')],
            },
        ),
        migrations.CreateModel(
            name='Contratto',
            fields=[
                ('id', models.BigAutoField(db_column='C_ID', primary_key=True, serialize=False)),
                ('data_ass', models.DateField()),
                ('data_fine', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('tipologia', models.CharField(max_length=100)),
                ('ore_sett', django.contrib.postgres.fields.ArrayField(base_field=models.DecimalField(decimal_places=2, max_digits=5), default=list, help_text='Ore nominali lun-ven, es: [8,8,8,8,8]', size=5, validators=[presenze.models.validate_ore_sett_len_5])),
                ('data_creaz', models.DateTimeField(default=django.utils.timezone.now)),
                ('data_upd', models.DateTimeField(auto_now=True)),
                ('utente', models.ForeignKey(db_column='U_ID', on_delete=django.db.models.deletion.CASCADE, related_name='contratti', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Contratto',
                'indexes': [models.Index(fields=['utente', 'is_active'], name='Contratto_U_ID_365f89_idx')],
            },
        ),
        migrations.CreateModel(
            name='Saldo',
            fields=[
                ('id', models.BigAutoField(db_column='S_ID', primary_key=True, serialize=False)),
                ('data', models.DateField()),
                ('valore_saldo_validato', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('valore_saldo_sospeso', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('data_creaz', models.DateTimeField(default=django.utils.timezone.now)),
                ('data_upd', models.DateTimeField(auto_now=True)),
                ('utente', models.ForeignKey(db_column='U_ID', on_delete=django.db.models.deletion.CASCADE, related_name='saldi', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Saldo',
                'indexes': [models.Index(fields=['utente', 'data'], name='Saldo_U_ID_170871_idx')],
            },
        ),
        migrations.CreateModel(
            name='TimeEntry',
            fields=[
                ('id', models.BigAutoField(db_column='TE_ID', primary_key=True, serialize=False)),
                ('type', models.IntegerField(choices=[(1, 'Lavoro ordinario'), (2, 'Ferie'), (3, 'Versamento banca ore'), (4, 'Prelievo banca ore'), (5, 'Malattia'), (6, 'Permesso ordinario'), (7, 'Permesso studio'), (8, 'Permesso 104'), (9, 'Permesso ex festività'), (10, 'Congedo maternità/paternità'), (11, 'Sciopero')])),
                ('ore_tot', models.DecimalField(decimal_places=2, max_digits=6)),
                ('data', models.DateField()),
                ('validation_level', models.IntegerField(choices=[(0, 'Compilato automaticamente'), (1, "Validato dall'utente"), (2, "Validato dall'amministratore")], default=0)),
                ('data_creaz', models.DateTimeField(default=django.utils.timezone.now)),
                ('data_upd', models.DateTimeField(auto_now=True)),
                ('utente', models.ForeignKey(db_column='U_ID', on_delete=django.db.models.deletion.CASCADE, related_name='time_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'TimeEntry',
                'indexes': [models.Index(fields=['utente', 'data'], name='TimeEntry_U_ID_e2fe60_idx'), models.Index(fields=['data', 'type'], name='TimeEntry_data_a5118a_idx')],
            },
        ),
        migrations.CreateModel(
            name='Trasferta',
            fields=[
                ('id', models.BigAutoField(db_column='T_ID', primary_key=True, serialize=False)),
                ('data', models.DateField()),
                ('coefficiente', models.DecimalField(decimal_places=4, default=0, max_digits=8)),
                ('tot_km', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('spesa_parcheggio', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('spesa_ristorante', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('spesa_albergo', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('spesa_biglietti', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('spesa_pedaggi', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('data_creaz', models.DateTimeField(default=django.utils.timezone.now)),
                ('data_upd', models.DateTimeField(auto_now=True)),
                ('automobile', models.ForeignKey(blank=True, db_column='A_ID', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trasferte', to='presenze.automobile')),
                ('utente', models.ForeignKey(db_column='U_ID', on_delete=django.db.models.deletion.CASCADE, related_name='trasferte', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Trasferta',
                'indexes': [models.Index(fields=['utente', 'data'], name='Trasferta_U_ID_572b84_idx'), models.Index(fields=['data'], name='Trasferta_data_7ea585_idx')],
            },
        ),
    ]
