# Generated by Django 5.2.6 on 2026-01-08 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presenze', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='utente',
            name='cognome',
            field=models.CharField(blank=True, max_length=75),
        ),
        migrations.AddField(
            model_name='utente',
            name='nome',
            field=models.CharField(blank=True, max_length=75),
        ),
    ]
