# Generated by Django 5.2.6 on 2026-01-13 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presenze', '0002_utente_cognome_utente_nome'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='timeentry',
            constraint=models.UniqueConstraint(fields=('utente', 'data', 'type'), name='uniq_timeentry_utente_data_type'),
        ),
    ]
