# Generated by Django 5.2.6 on 2026-01-28 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presenze', '0003_timeentry_uniq_timeentry_utente_data_type'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='saldo',
            constraint=models.UniqueConstraint(fields=('utente', 'data'), name='uniq_saldo_utente_data'),
        ),
    ]
