# Generated by Django 5.2.6 on 2026-01-28 13:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presenze', '0004_saldo_uniq_saldo_utente_data'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='saldo',
            name='uniq_saldo_utente_data',
        ),
        migrations.RemoveIndex(
            model_name='saldo',
            name='Saldo_U_ID_170871_idx',
        ),
        migrations.RemoveField(
            model_name='saldo',
            name='data',
        ),
        migrations.AlterField(
            model_name='saldo',
            name='utente',
            field=models.OneToOneField(db_column='U_ID', on_delete=django.db.models.deletion.CASCADE, related_name='saldo', to=settings.AUTH_USER_MODEL),
        ),
    ]
