# Generated by Django 5.2.6 on 2026-01-28 13:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presenze', '0005_remove_saldo_uniq_saldo_utente_data_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saldo',
            name='utente',
            field=models.OneToOneField(db_column='U_ID', on_delete=django.db.models.deletion.CASCADE, related_name='saldi', to=settings.AUTH_USER_MODEL),
        ),
    ]
