# Generated by Django 5.2.6 on 2026-01-28 14:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presenze', '0006_alter_saldo_utente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saldo',
            name='utente',
            field=models.OneToOneField(db_column='U_ID', on_delete=django.db.models.deletion.CASCADE, related_name='saldo', to=settings.AUTH_USER_MODEL),
        ),
    ]
