# Generated by Django 5.2.6 on 2026-01-30 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presenze', '0007_alter_saldo_utente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeentry',
            name='type',
            field=models.IntegerField(choices=[(1, 'Lavoro ordinario'), (2, 'Ferie'), (3, 'Versamento banca ore'), (4, 'Prelievo banca ore'), (5, 'Malattia'), (6, 'Permesso ordinario'), (7, 'Permesso studio'), (8, 'Permesso 104'), (9, 'Permesso ex festività'), (10, 'Congedo maternità/paternità'), (11, 'Sciopero'), (12, 'Festivita')]),
        ),
    ]
