# Generated by Django 5.2.6 on 2026-02-05 14:30

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presenze', '0008_alter_timeentry_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Spesa',
            fields=[
                ('id', models.BigAutoField(db_column='S_ID', primary_key=True, serialize=False)),
                ('type', models.IntegerField(choices=[('1', 'Pedaggi'), ('2', 'Rimborso km'), ('3', 'Ristoranti'), ('4', 'Albergo'), ('5', 'Parcheggi'), ('6', 'Aerei/treni'), ('7', 'Altro')])),
                ('importo', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('data_creaz', models.DateTimeField(default=django.utils.timezone.now)),
                ('data_upd', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'Spesa',
            },
        ),
        migrations.RemoveField(
            model_name='trasferta',
            name='spesa_albergo',
        ),
        migrations.RemoveField(
            model_name='trasferta',
            name='spesa_biglietti',
        ),
        migrations.RemoveField(
            model_name='trasferta',
            name='spesa_parcheggio',
        ),
        migrations.RemoveField(
            model_name='trasferta',
            name='spesa_pedaggi',
        ),
        migrations.RemoveField(
            model_name='trasferta',
            name='spesa_ristorante',
        ),
        migrations.RemoveField(
            model_name='trasferta',
            name='tot_km',
        ),
        migrations.AddField(
            model_name='timeentry',
            name='note',
            field=models.TextField(blank=True, help_text='Inserisci eventuali dettagli sulla trasferta', null=True, verbose_name='Note aggiuntive'),
        ),
        migrations.AddField(
            model_name='trasferta',
            name='azienda',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='trasferta',
            name='indirizzo',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='trasferta',
            name='note',
            field=models.TextField(blank=True, help_text='Inserisci eventuali dettagli sulla trasferta', null=True, verbose_name='Note aggiuntive'),
        ),
        migrations.AddField(
            model_name='trasferta',
            name='validation_level',
            field=models.IntegerField(choices=[(1, "Validato dall'utente"), (2, "Validato dall'amministratore")], default=1),
        ),
        migrations.AlterField(
            model_name='timeentry',
            name='type',
            field=models.IntegerField(choices=[(1, 'Lavoro ordinario'), (2, 'Ferie'), (3, 'Versamento banca ore'), (4, 'Prelievo banca ore'), (5, 'Malattia'), (6, 'Permesso ordinario'), (7, 'Permesso studio'), (8, 'Permesso 104'), (9, 'Permesso ex festività'), (10, 'Permesso R.O.L.'), (11, 'Congedo maternità/paternità'), (12, 'Sciopero'), (13, 'Festività')]),
        ),
        migrations.AddIndex(
            model_name='trasferta',
            index=models.Index(fields=['azienda'], name='Trasferta_azienda_915f02_idx'),
        ),
        migrations.AddField(
            model_name='spesa',
            name='trasferta',
            field=models.ForeignKey(db_column='T_ID', on_delete=django.db.models.deletion.CASCADE, related_name='spese', to='presenze.trasferta'),
        ),
        migrations.AddIndex(
            model_name='spesa',
            index=models.Index(fields=['trasferta'], name='Spesa_T_ID_9f82ff_idx'),
        ),
        migrations.AddIndex(
            model_name='spesa',
            index=models.Index(fields=['type'], name='Spesa_type_6baa42_idx'),
        ),
    ]
