# Generated by Django 5.2.6 on 2026-03-09 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("presenze", "0009_spesa_remove_trasferta_spesa_albergo_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="trasferta",
            name="coefficiente",
        ),
    ]
