# Generated by Codex on 2026-03-09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("presenze", "0010_remove_trasferta_coefficiente"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql=(
                        'ALTER TABLE "Automobile" '
                        "ADD COLUMN IF NOT EXISTS is_active boolean NOT NULL DEFAULT TRUE;"
                    ),
                    reverse_sql=(
                        'ALTER TABLE "Automobile" '
                        "DROP COLUMN IF EXISTS is_active;"
                    ),
                ),
                migrations.RunSQL(
                    sql=(
                        'ALTER TABLE "Automobile" '
                        "ADD COLUMN IF NOT EXISTS coefficiente numeric(8,4) NOT NULL DEFAULT 0;"
                    ),
                    reverse_sql=(
                        'ALTER TABLE "Automobile" '
                        "DROP COLUMN IF EXISTS coefficiente;"
                    ),
                ),
            ],
            state_operations=[
                migrations.AddField(
                    model_name="automobile",
                    name="is_active",
                    field=models.BooleanField(default=True),
                ),
                migrations.AddField(
                    model_name="automobile",
                    name="coefficiente",
                    field=models.DecimalField(decimal_places=4, default=0, max_digits=8),
                ),
            ],
        ),
    ]
