# Generated by Django 5.2.6 on 2026-04-15 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presenze', '0017_alter_utilitiesbar_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spesa',
            name='type',
            field=models.IntegerField(choices=[(1, 'Pedaggi'), (2, 'Rimborso km'), (3, 'Ristoranti'), (4, 'Albergo'), (5, 'Parcheggi'), (6, 'Aerei/treni'), (7, 'Altro')]),
        ),
        migrations.AlterField(
            model_name='timeentry',
            name='type',
            field=models.IntegerField(choices=[(1, 'Lavoro ordinario'), (2, 'Ferie'), (3, 'Versamento banca ore'), (4, 'Prelievo banca ore'), (5, 'Malattia'), (6, 'Permesso ordinario'), (7, 'Permesso studio'), (8, 'Permesso 104'), (9, 'Permesso ex festività'), (10, 'Permesso R.O.L.'), (11, 'Congedo maternità/paternità'), (12, 'Sciopero'), (13, 'Festività'), (14, 'Visite mediche L.106/25')]),
        ),
    ]
