# Generated by Django 5.2.6 on 2026-08-03 08:52

import django.contrib.postgres.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presenze', '0027_jira_reference_name_ci_unique'),
    ]

    operations = [
        migrations.CreateModel(
            name='JiraGlobals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(max_length=255)),
                ('filters', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, default=list, help_text='Filtri globali Jira (array di stringhe)', size=None)),
                ('JiraControl', models.BooleanField(default=True, help_text='Abilita/disabilita il controllo ore Jira nella generazione PDF presenze.')),
            ],
            options={
                'db_table': 'JiraGlobals',
            },
        ),
        migrations.AlterField(
            model_name='utilitiesbar',
            name='icon',
            field=models.CharField(choices=[('faConfluence', 'Confluence'), ('faJira', 'Jira'), ('faCircle', 'Circle'), ('faAmazon', 'Amazon'), ('faAws', 'AWS'), ('faDiscord', 'Discord'), ('faGithub', 'GitHub'), ('faGitlab', 'GitLab'), ('faLinkedin', 'LinkedIn'), ('faMicrosoft', 'Microsoft'), ('faNotion', 'Notion'), ('faUbuntu', 'Ubuntu'), ('faBookOpen', 'Book Open'), ('faMagnifyingGlass', 'Magnifying Glass')], help_text='Nome icona Font Awesome consentita', max_length=100),
        ),
        migrations.CreateModel(
            name='JiraCredentials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jira_email', models.CharField(max_length=255)),
                ('_jira_token', models.TextField(db_column='jira_token')),
                ('utente', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='jira_credentials', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
